### ISSUE TITLE
Problems installing with pip

### ISSUE THREAD

**Issue by pselle** [iopipe/iopipe-python#26]
It looks like the requirements.txt is missing from the package uploaded to pip

```
Collecting iopipe (from -r requirements.txt (line 1))
  Using cached iopipe-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/download.py", line 421, in get_file_content
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3t/vw8l_45s3bsb4rz3c2l9wvh00000gn/T/pip-build-3822khjv/iopipe/setup.py", line 8, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/private/var/folders/3t/vw8l_45s3bsb4rz3c2l9wvh00000gn/T/pip-build-3822khjv/iopipe/setup.py", line 8, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/req/req_file.py", line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/download.py", line 425, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: './requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3t/vw8l_45s3bsb4rz3c2l9wvh00000gn/T/pip-build-3822khjv/iopipe/```

**Comment by ewindisch** [comment]
requirements.txt now included.
