### ISSUE TITLE
Signal.sigalrm failure on Windows with local invoke

### ISSUE THREAD

**Issue by ewindisch** [iopipe/iopipe-python#311]
```Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Program Files (x86)\Python36-32\lib\unittest\case.py", line 601, in run
    testMethod()
  File "C:\Users\mikk.laos\PycharmProjects\api\background-check-request\test\integration\test_app.py", line 28, in test_whenNoJSONBOdy_shouldReturnJsonNotParsebleError
    body='')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\chalice\local.py", line 486, in handle_request
    response = self._app_object(lambda_event, lambda_context)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\iopipe\agent.py", line 120, in wrapped
    signal.signal(signal.SIGALRM, self.handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

**Comment by ewindisch** [comment]
@kolanos there's a user blocked on this, if we can get it squeezed in. Thanks!
